[package]
name = "kuznyechik"
version = "0.1.0"
edition = "2018"

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
galois_2p8 = "0.1.0"
encoding_rs = "0.8"
rayon = "1.6"
rand = "0.8"
rand_core = "0.6"
rand_chacha = "0.3"

[[bin]]
name = "kuznyechik"
path = "kuznyechik.rs"
